EventTicket/Controllers/MyanmarITStarController.cs
using EventTicket.App_Code;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EventTicket.Controllers
{
    public class MyanmarITStarController : Controller
    {
        DBBase db = new DBBase();Tree t = new Tree();
        // GET: MyanmarITStar
        public ActionResult Dashboard()
        {
            return View();
        }

        #region Accept Active
        public ActionResult AcceptActive()
        {
            if (Session["CurrentUserID"] == null)
            {
                Response.Redirect("~/Account/LoginForm");
            }
            //int ID = Convert.ToInt32(Request.QueryString["ID"]);
            //int MemberID = db.getIntByQuery("select * from RequestActive where ID="+ID, "MemberID");
            //db.ChangeByQuery("update Member set Active='True' where ID="+MemberID);
            return View();
        }
        public ActionResult AcceptRequest()
        {
            if (Session["CurrentUserID"] == null)
            {
                Response.Redirect("~/Account/LoginForm");
            }
            int ID = Convert.ToInt32(Request.QueryString["ID"]);
            int MemberID = Convert.ToInt32(Request.QueryString["MemberID"]);
            //Delete and Change Active in Member Table
            db.ChangeByQuery("delete from RequestActive where ID=" + ID);
            db.ChangeByQuery("delete from InactiveCount where MemberID=" + ID);
            db.ChangeByQuery("update Member set Active='True' where ID=" + MemberID);
          
            return RedirectToAction("AcceptActive");
        }
        public ActionResult RejectRequest()
        {
            if (Session["CurrentUserID"] == null)
            {
                Response.Redirect("~/Account/LoginForm");
            }
            int ID = Convert.ToInt32(Request.QueryString["ID"]);
            int MemberID = Convert.ToInt32(Request.QueryString["MemberID"]);
            //Delete 
            db.ChangeByQuery("delete from RequestActive where ID=" + ID);
            return RedirectToAction("AcceptActive");
        }
        #endregion

        #region Notification
        public ActionResult Notification()
        {
            if (Session["CurrentUserID"] == null)
            {
                Response.Redirect("~/Account/LoginForm");
            }
            return View();
        }
        public ActionResult SeeRequestActiveByBank()
        {
            if (Session["CurrentUserID"] == null)
            {
                Response.Redirect("~/Account/LoginForm");
            }
            return View();
        }
        public ActionResult AcceptRequestByBank()
        {
            if (Session["CurrentUserID"] == null)
            {
                Response.Redirect("~/Account/LoginForm");
            }
            int ID = Convert.ToInt32(Request.QueryString["ID"]);
            int MemberID = Convert.ToInt32(Request.QueryString["MemberID"]);
            string Email = db.getStringByQuery("select * from Member where ID=" + MemberID, "Email");

            db.ChangeByQuery("update RequestActiveDepositHistory set Proof='True' where ID=" + ID);
            db.ChangeByQuery("delete from InactiveCount where MemberID=" + ID);
            db.ChangeByQuery("update Member set Active='True' where ID=" + MemberID);
            //Send Mail
            string MailBody = "Dear " + db.getStringByQuery("select * from Member where ID=" + MemberID, "Name") + ",<br><br> We approved your active request deposited by bank.Your Account is now worked account. Your Account should turn to green. If it is not green, contact us.<br><br>Kind Regards,<br>Myanmar IT Star Company Limited";
            t.SendEmail("Request Active By Bank-DM Group", MailBody, Email);
            return RedirectToAction("SeeRequestActiveByBank");
        }
        public ActionResult RejectRequestByBank()
        {
            if (Session["CurrentUserID"] == null)
            {
                Response.Redirect("~/Account/LoginForm");
            }
            int ID = Convert.ToInt32(Request.QueryString["ID"]);
            db.ChangeByQuery("delete from RequestActiveDepositHistory where ID=" + ID);
            return RedirectToAction("SeeRequestActiveByBank");
        }
        #region Withdraw Request
        public ActionResult WithdrawRequest()
        {
            if (Session["CurrentUserID"] == null)
            {
                Response.Redirect("~/Account/LoginForm");
            }
            return View();
        }
        public ActionResult AcceptWithdrawRequest()
        {
            if (Session["CurrentUserID"] == null)
            {
                Response.Redirect("~/Account/LoginForm");
            }
            int WithdrawHistoryID = Convert.ToInt32(Request.QueryString["ID"]);
            int MemberID = Convert.ToInt32(Request.QueryString["MemberID"]);
            int MemberBankID = db.getIntByQuery("select * from WithdrawHistory where ID="+WithdrawHistoryID, "MemberBankID");
            int BankID = db.getIntByQuery("select * from MemberBank where ID=" + MemberBankID, "BankID");

            string Email = db.getStringByQuery("select * from Member where ID=" + MemberID, "Email");
            int WithdrawedAmount = db.getIntByQuery("select * from WithdrawHistory where ID="+WithdrawHistoryID, "WithdrawedAmount");
            db.ChangeByQuery("update Wallet set Balance=Balance-"+WithdrawedAmount+"  where MemberID="+MemberID);
            db.ChangeByQuery("update WithdrawHistory set Proof='True' where ID="+WithdrawHistoryID+" and MemberID="+MemberID);
            string MailBody = "Dear " + db.getStringByQuery("select * from Member where ID=" + MemberID, "Name") + ",<br><br> We have sent "+ WithdrawedAmount + "Ks to your bank account " + db.getStringByQuery("select * from Bank where ID=" + BankID, "Name") + " Account (" + db.getStringByQuery("select * from MemberBank where ID=" + MemberBankID, "AccountNumber") + ").<br><br>Kind Regards,<br>Myanmar IT Star Company Limited";
            t.SendEmail("Withdraw Fund Sent-DM Group", MailBody, Email);
            return RedirectToAction("WithdrawRequest");
        }
        public ActionResult RejectWithdrawRequest()
        {
            if (Session["CurrentUserID"] == null)
            {
                Response.Redirect("~/Account/LoginForm");
            }
            int WithdrawHistoryID = Convert.ToInt32(Request.QueryString["ID"]);
            int MemberID = Convert.ToInt32(Request.QueryString["MemberID"]);
            int MemberBankID = db.getIntByQuery("select * from WithdrawHistory where ID=" + WithdrawHistoryID, "MemberBankID");
            int BankID = db.getIntByQuery("select * from MemberBank where ID=" + MemberBankID, "BankID");

            string Email = db.getStringByQuery("select * from Member where ID=" + MemberID, "Email");
            int WithdrawedAmount = db.getIntByQuery("select * from WithdrawHistory where ID=" + WithdrawHistoryID, "WithdrawedAmount");
            db.ChangeByQuery("delete From WithdrawHistory where ID="+WithdrawHistoryID);
            string MailBody = "Dear " + db.getStringByQuery("select * from Member where ID=" + MemberID, "Name") + ",<br><br> We have Rejected of Withdrawing " + WithdrawedAmount + "Ks to your bank account [" + db.getStringByQuery("select * from Bank where ID=" + BankID, "Name") + " Account (" + db.getStringByQuery("select * from MemberBank where ID=" + MemberBankID, "AccountNumber") + ") because bank account name does not matched with your name.<br><br>Kind Regards,<br>Myanmar IT Star Company Limited";
            t.SendEmail("Withdraw Fund Rejected-DM Group", MailBody, Email);
            return RedirectToAction("WithdrawRequest");
        }
        #endregion

        #endregion

        public ActionResult ViewAllMembers()
        {
            if (Session["CurrentUserID"] == null)
            {
                Response.Redirect("~/Account/LoginForm");
            }
            if (TempData["From"] != null)
            {
                ViewBag.From = TempData["From"].ToString();
                ViewBag.To = TempData["To"].ToString();
            }
            else
            {
                ViewBag.From = 0;
                ViewBag.To = 10;
            }
            return View();
        }
        public ActionResult ProcessViewAllMembers()
        {
            if (Session["CurrentUserID"] == null)
            {
                Response.Redirect("~/Account/LoginForm");
            }

            string From = Request.Form["From"];
            string To = Request.Form["To"];
            TempData["From"] = From;
            TempData["To"] = To;

            return RedirectToAction("ViewAllMembers");
        }
    }
}

EventTicket/Views/MyanmarITStar/AcceptActive.cshtml
@using EventTicket.App_Code;
@using System.Data;
@{
    ViewBag.Title = "DM Group - Onine Home Jobs Program";
    Layout = "~/Views/Shared/MyanmarITStar.cshtml";
    Base b = new Base();int i = 1;
    DataTable dt = b.getAllByQuery("select * from RequestActive");
}
<div class="contentBodyBox">
    @*<font color="#8B7D6B" class="zg">The following are all registered members.</font><br /><br />*@
    <table id="displayTable" class="table table-bordered">
        <thead><tr><th><span class="zg">No</span></th><th><span class="zg">DM Email</span>​</th><th>2Captcha Email</th><th><span class="zg">Phone</span></th><th>Accept/Reject</th></tr></thead>
        <tbody>
            @{
                foreach (DataRow row in dt.Rows)
                {
                    int MemberID = Convert.ToInt32(row["MemberID"]);
                    <tr><td>@i</td><td><font class="normalText"><span class="zg">@b.getStringByQuery("select * from Member where ID="+MemberID,"Email")</span></font></td><td>@b.getStringByQuery("select * from MemberCaptchaEmail where MemberID="+MemberID, "CaptchaEmail")</td><td><font class="normalText"><span class="zg">@b.getStringByQuery("select * from Member where ID="+MemberID,"Phone")</span></font></td><td><a href="~/MyanmarITStar/AcceptRequest?ID=@row["ID"]&MemberID=@MemberID"><span class="label label-success">Accept</span></a>&nbsp;&nbsp;<a href="~/MyanmarITStar/RejectRequest?ID=@row["ID"]&MemberID=@MemberID"><span class="label label-danger">Reject</span></a></td></tr>
                    i++;
                }
            }
        </tbody>
    </table>
</div>

EventTicket/Views/MyanmarITStar/Dashboard.cshtml
@using EventTicket.App_Code;
@using System.Data;
@{
    Base b = new Base();
    ViewBag.Title = "DM Group - Onine Home Jobs Program";
    Layout = "~/Views/Shared/MyanmarITStar.cshtml";
}

<div class="row">
    <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-aqua">
            <div class="inner">
                <h3>@b.getCountByQuery("select * from Member where Date='" +DateTime.Now.ToString("MM.dd.yyyy")+ "'")</h3>
                <p><span class="zg">Today Members</span></p>
            </div>
            <div class="icon">
                <i class="fa fa-bar-chart"></i>
            </div>
            <a href="" class="small-box-footer">​<span class="zg">More Info​ </span><i class="fa fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-aqua">
            <div class="inner">
                <h3>@b.getCountByQuery("select * from Member")</h3>
                <p><span class="zg">Total Members</span></p>
            </div>
            <div class="icon">
                <i class="fa fa-bar-chart"></i>
            </div>
            <a href="" class="small-box-footer">​<span class="zg">More Info​ </span><i class="fa fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <!-- ./col -->
    <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-green">
            <div class="inner">
                <h3>@b.getCountByQuery("select * from Member where Active='True'")<sup style="font-size: 20px"></sup></h3>
                <p><span class="zg">Active</span></p>
            </div>
            <div class="icon">
                <i class="fa fa-bar-chart"></i>
            </div>
            <a href="" class="small-box-footer"><span class="zg">More Info</span> <i class="fa fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-red">
            <div class="inner">
                <h3>@b.getCountByQuery("select * from Member where Active='False'")</h3>
                <p>InActive</p>
            </div>
            <div class="icon">
                <i class="fa fa-pie-chart"></i>
            </div>
            <a href="" class="small-box-footer">More info<i class="fa fa-arrow-circle-right"></i></a>
        </div>
    </div>
</div>

EventTicket/Views/MyanmarITStar/Notification.cshtml
@using EventTicket.App_Code;
@using System.Data;
@{
    ViewBag.Title = "Setting";
    Layout = "~/Views/Shared/MyanmarITStar.cshtml";
    Base b = new Base();int OneMonthInactiveCount = 0;
    DataTable InactiveMember = b.getAllByQuery("select * from Member where Active='False'");
    foreach(DataRow row in InactiveMember.Rows){
        int MemberID = Convert.ToInt32(row["ID"]);
        int Count = b.getCountByQuery("select * from InactiveCount where MemberID=" + MemberID);
        if(Count == 2)
        {
            OneMonthInactiveCount++;
        }
    }
}
<div>
    <div class="box-body">      
        <a class="btn btn-app" href="~/MyanmarITStar/AcceptActive">
            <span class="badge bg-yellow">@b.getCountByQuery("select * from RequestActive")</span>
            <i class="fa fa-repeat"></i> Active Requests By 2Captcha
        </a>
        <a class="btn btn-app" href="~/MyanmarITStar/SeeRequestActiveByBank">
            <span class="badge bg-yellow">@b.getCountByQuery("select * from RequestActiveDepositHistory where Proof='False'")</span>
            <i class="fa fa-repeat"></i> Active Requests By Bank 
        </a>
        <a class="btn btn-app" href="~/MyanmarITStar/WithdrawRequest">
            <span class="badge bg-green">@b.getCountByQuery("select * from WithdrawHistory where Proof='False'")</span>
            <i class="fa fa-money"></i> Withdraw Requests
        </a>
       <a class="btn btn-app">
            <span class="badge bg-purple">@OneMonthInactiveCount</span>
            <i class="fa fa-users"></i>1 month Inactive 
        </a>
@*
    <a class="btn btn-app">
        <span class="badge bg-teal">67</span>
        <i class="fa fa-inbox"></i> Orders
    </a>
    <a class="btn btn-app">
        <span class="badge bg-aqua">12</span>
        <i class="fa fa-envelope"></i> Inbox
    </a>
    <a class="btn btn-app">
        <span class="badge bg-red">531</span>
        <i class="fa fa-heart-o"></i> Likes
    </a>*@
    </div>
</div>

EventTicket/Views/MyanmarITStar/SeeRequestActiveByBank.cshtml
@using EventTicket.App_Code;
@using System.Data;
@{
    ViewBag.Title = "DM Group - Onine Home Jobs Program";
    Layout = "~/Views/Shared/MyanmarITStar.cshtml";
    Base b = new Base(); int i = 1;
    DataTable dt = b.getAllByQuery("select * from RequestActiveDepositHistory where Proof='False'");
}
<div class="contentBodyBox">
    @*<font color="#8B7D6B" class="zg">The following are all registered members.</font><br /><br />*@
    <table id="displayTable" class="table table-bordered">
        <thead><tr><th><span class="zg">No</span></th><th><span class="zg">Name</span>​</th><th>Account Number</th><th><span class="zg">Amount</span></th><th>Accept/Reject</th></tr></thead>
        <tbody>
            @{
                foreach (DataRow row in dt.Rows)
                {
                    int MemberBankID = Convert.ToInt32(row["MemberBankID"]);
                    int BankID = b.getIntByQuery("select * from MemberBank where ID=" + MemberBankID, "BankID");
                    int MemberID = Convert.ToInt32(row["MemberID"]);
                    string AccountNumber = b.getStringByQuery("select * from MemberBank where ID=" + MemberBankID, "AccountNumber") +"("+b.getStringByQuery("select * from Bank where ID="+BankID,"Name")+")";
                    <tr><td>@i</td><td><font class="normalText"><span class="zg">@b.getStringByQuery("select * from Member where ID=" + MemberID, "Name")</span></font></td><td>@AccountNumber</td><td><font class="normalText"><span class="zg">7500</span></font></td><td><a href="~/MyanmarITStar/AcceptRequestByBank?ID=@row["ID"]&MemberID=@MemberID"><span class="label label-success">Accept</span></a>&nbsp;&nbsp;<a href="~/MyanmarITStar/RejectRequestByBank?ID=@row["ID"]&MemberID=@MemberID"><span class="label label-danger">Reject</span></a></td></tr>
                    i++;
                }
            }
        </tbody>
    </table>
</div>

EventTicket/Views/MyanmarITStar/ViewAllMembers.cshtml
@using EventTicket.App_Code;
@using System.Data;
@{
    int i = 1;
    Base b = new Base();
    Node n = new Node();
    DataTable Member = b.getAllByQuery("select * from Member ORDER BY ID ASC OFFSET " + ViewBag.From + " ROWS FETCH NEXT " + ViewBag.To + " ROWS ONLY");
    ViewBag.Title = "DM Group - Onine Home Jobs Program";
    Layout = "~/Views/Shared/MyanmarITStar.cshtml";
}

@using (Html.BeginForm("ProcessViewAllMembers", "MyanmarITStar"))
{
    <div class="contentFormBox">
        <div class="row">
            <div class="col-md-4">
                <div class="input-group">
                    <div class="input-group-addon">
                        <i class="fa fa-database"></i>
                    </div>
                    <input type="text" name="From" class="form-control" value="@ViewBag.From" required>
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class="fa fa-database"></i>
                        </div>
                        <input type="text" name="To" class="form-control" value="@ViewBag.To" required>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <div class="input-group">
                        <center> <span class="zg"><input type="submit" class="btn btn-primary" value="SEE" /></span></center>
                    </div>
                </div>
            </div>
        </div>
    </div>
}
<div class="contentBodyBox">
    @*<font color="#8B7D6B" class="zg">The following are all registered members.</font><br /><br />*@
    <table id="displayTable" class="table table-bordered">
        <thead><tr><th><span class="zg">No</span></th><th>MemberID</th><th><span class="zg">Name</span>​</th><th><span class="zg">Phone</span></th><th><span class="zg">Address</span></th><th><span class="zg">Email</span></th><th>Level 1,2,3</th><th>FB</th></tr></thead>
        <tbody>
            @{
                foreach (DataRow rows in Member.Rows)
                {
                    int MemberID = Convert.ToInt32(rows["ID"]);
                    <tr><td><span class="zg">@i</span></td><td>@MemberID</td><td><font class="normalText"><span class="zg">@rows["Name"]</span></font></td><td><font class="normalText"><span class="zg">@rows["Phone"]</span></font></td><td><span class="zg">@rows["Address"]</span></td><td><span class="zg">@rows["Email"]</span></td><td>@n.GetTotalNode(MemberID,0) | @n.GetTotalNode(MemberID, 1) , @n.GetTotalNode(MemberID, 2) , @n.GetTotalNode(MemberID, 3)</td><td><a href="@rows["FBLink"]">Click</a></td></tr>
                    i++;
                }
            }
        </tbody>
    </table>
</div>

EventTicket/Views/MyanmarITStar/WithdrawRequest.cshtml
@using EventTicket.App_Code;
@using System.Data;
@{
    ViewBag.Title = "DM Group - Onine Home Jobs Program";
    Layout = "~/Views/Shared/MyanmarITStar.cshtml";
    Base b = new Base(); int i = 1;
    DataTable dt = b.getAllByQuery("select * from WithdrawHistory where Proof='False'");
}
<div class="contentBodyBox"> <table id="displayTable" class="table table-bordered">
        <thead><tr><th><span class="zg">No</span></th><th><span class="zg">Name</span>​</th><th><span class="zg">Phone</span></th><th><span class="zg">Bank Account</span></th><th><span class="zg">Withdraw Amount</span></th><th>Accept/Reject</th></tr></thead>
        <tbody>
            @{
                foreach (DataRow row in dt.Rows)
                {
                    int MemberID = Convert.ToInt32(row["MemberID"]);
                    int WithdrawAmount = Convert.ToInt32(row["WithdrawedAmount"]);
                    int MemberBankID = Convert.ToInt32(row["MemberBankID"]);
                    int BankID = b.getIntByQuery("select * from MemberBank where ID="+MemberBankID, "BankID");
                    string BankName = b.getStringByQuery("select * from Bank where ID="+BankID, "Name");
                    string AccountNumber = b.getStringByQuery("select * from MemberBank where ID=" + MemberBankID, "AccountNumber");
             <tr><td>@i</td>
            <td><font class="normalText"><span class="zg">@b.getStringByQuery("select * from Member where ID="+MemberID,"Name")</span></font></td>
            <td><font class="normalText"><span class="zg">@b.getStringByQuery("select * from Member where ID=" + MemberID, "Phone")</span></font></td>
            <td><font class="normalText"><span class="zg">@AccountNumber [@BankName]</span></font></td>
            <td><span class="zg">@WithdrawAmount</span></td>
            <td>
                 <a href="~/MyanmarITStar/AcceptWithdrawRequest?ID=@row["ID"]&MemberID=@MemberID"><span class="label label-success">Accept</span></a>&nbsp;&nbsp;
                 <a href="~/MyanmarITStar/RejectWithdrawRequest?ID=@row["ID"]&MemberID=@MemberID"><span class="label label-danger">Reject</span></a>
           </td></tr>
                    i++;
                }
            }
        </tbody>
    </table>
</div>