EventTicket/Models/ManageViewModels.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;

namespace EventTicket.Models
{
    public class IndexViewModel
    {
        public bool HasPassword { get; set; }
        public IList<UserLoginInfo> Logins { get; set; }
        public string PhoneNumber { get; set; }
        public bool TwoFactor { get; set; }
        public bool BrowserRemembered { get; set; }
    }

    public class ManageLoginsViewModel
    {
        public IList<UserLoginInfo> CurrentLogins { get; set; }
        public IList<AuthenticationDescription> OtherLogins { get; set; }
    }

    public class FactorViewModel
    {
        public string Purpose { get; set; }
    }

    public class SetPasswordViewModel
    {
        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm new password")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

    public class ChangePasswordViewModel
    {
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Current password")]
        public string OldPassword { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm new password")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

    public class AddPhoneNumberViewModel
    {
        [Required]
        [Phone]
        [Display(Name = "Phone Number")]
        public string Number { get; set; }
    }

    public class VerifyPhoneNumberViewModel
    {
        [Required]
        [Display(Name = "Code")]
        public string Code { get; set; }

        [Required]
        [Phone]
        [Display(Name = "Phone Number")]
        public string PhoneNumber { get; set; }
    }

    public class ConfigureTwoFactorViewModel
    {
        public string SelectedProvider { get; set; }
        public ICollection<System.Web.Mvc.SelectListItem> Providers { get; set; }
    }
}

EventTicket/Controllers/EOrgController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EventTicket.App_Code;
using System.Data;
using System.Net;

namespace EventTicket.Controllers
{
    public class EOrgController : Controller
    {
        int EOrgID = 1;//Convert.ToInt32(Session["CurrentUserID"]);

        DecryptParameter dp = new DecryptParameter();
        DBBase d = new DBBase();
        public ActionResult Index()
        {
            return View();
        }

        //CreateEvent, AddEventData, DeleteEvent, Manage, NotFound, Reset Event, Edit Event
        #region Event
        public ActionResult CreateEvent()
        {
            if(Session["CurrentUserID"]== null)
            {
                Response.Redirect("~/Login/LoginForm");
            }
            return View();
        }

        [HttpPost]
        public ActionResult AddEventData(HttpPostedFileBase file, HttpPostedFileBase fileMap)
        {
            EOrgID = Convert.ToInt32(Session["CurrentUserID"]);
            string ImageName = "";
            String ImageNameMap = "";
            if (file.ContentLength > 0)
            {
                var fileName = System.IO.Path.GetFileName(file.FileName);
                ImageName = fileName;
                var path = System.IO.Path.Combine(Server.MapPath("~/Image/Cover"), fileName);
                file.SaveAs(path);
            }
            if (fileMap.ContentLength > 0)
            {
                var fileNameMap = System.IO.Path.GetFileName(fileMap.FileName);
                ImageNameMap = fileNameMap;
                var path = System.IO.Path.Combine(Server.MapPath("~/Image/Seat_Map"), fileNameMap);
                fileMap.SaveAs(path);
            }
            string Name = Request.Form["Name"];
            string Category = Request.Form["Category"];
            string Date = Request.Form["Date"];
            string Time = Request.Form["Time"];
            string Place = Request.Form["Place"];
            string Email = Request.Form["Email"];
            string Phone = Request.Form["Phone"];
            string IsFree = Request.Form["isFree"];
            string IsPublic = Request.Form["isPublic"];
            string TownID = Request.Form["Town"];
            string Town = d.getStringByQuery("select * from Town where ID="+TownID, "Name");
            int Row = Convert.ToInt16(Request["Row"]);
            int TotalTicket = 0;//Convert.ToInt32(Request.Form["TotalTicket"]);
            string Description = Request.Form["Description"];
            //Get EOrgID. Set to 1 in unit testing
            int ECategoryID = Convert.ToInt32(Category);
            DateTime EDate = Convert.ToDateTime(Date);
            d.ChangeByQuery("insert into Event(EOrgID,ECategoryID,Name,ImageName,Place,EDate,Email,Phone,TotalTicket,IsFree,Description,Row,SeatMap,Time,Town,IsPublic) values(" + EOrgID + "," + ECategoryID + ",N'" + Name + "','" + ImageName + "','" + Place + "','" + EDate + "','" + Email + "','" + Phone + "','" + TotalTicket + "','" + IsFree + "','" + Description + "'," + Row + ",'"+ ImageNameMap + "','"+Time+"','"+Town+"','"+IsPublic+"')");
            int EID = d.getIntByQuery("select top 1 * From Event where EOrgID=" + EOrgID + " order by ID desc", "ID");
            Row r = new Row();
            r.set(EID, Row);
            //Seat s = new Seat();
            //s.setTotalTicket(TotalTicket, 1);
            //s.setFirstTimeSeat();
            return RedirectToAction("Manage");
        }
        public ActionResult DeleteEvent()
        {
            string E_EID = Request.QueryString["E_EID"];
            E_EID = E_EID.Replace(" ", "+");
            String EID = dp.Decrypt(E_EID, "ETicket");
            int ID = Convert.ToInt32(EID);
            //Delete Cover and SeatMap
            string Cover = d.getStringByQuery("select * from Event where ID=" + ID, "ImageName");
            string SeatMap = d.getStringByQuery("select * from Event where ID=" + ID, "SeatMap");
            DeleteCover(Cover);DeleteSeatMap(SeatMap);
            //(1) Delete Event, Row, Seat, CustomerTicket
            d.ChangeByQuery("delete from CustomerTicket where SeatID in(select ID from Seat where EID=" + ID + ")");
            d.ChangeByQuery("delete from Seat where EID=" + ID);
            d.ChangeByQuery("delete from Row where EID=" + ID);
            d.ChangeByQuery("delete from Event where ID=" + ID);
            return RedirectToAction("Manage");
        }
        public ActionResult ResetEvent()
        {
            string E_EID = Request.QueryString["E_EID"];
            E_EID = E_EID.Replace(" ", "+");
            String EID = dp.Decrypt(E_EID, "ETicket");
            int ID = Convert.ToInt32(EID);
            //Delete CustomerTicket, Clear Seat Status
            d.ChangeByQuery("delete from CustomerTicket where SeatID in(select ID from Seat where EID=" + ID + ")");
            d.ChangeByQuery("update Seat set Status='Free' where EID=" + ID);
            return RedirectToAction("Manage");
        }
        public ActionResult EditEvent()
        {
            string E_EID = Request.QueryString["E_EID"];
            E_EID = E_EID.Replace(" ", "+");
            String EID = dp.Decrypt(E_EID, "ETicket");
            int ID = Convert.ToInt32(EID);
            //Put EID to viewbag and return to Edit form
            ViewBag.EID = ID;
            return View();
        }
        public ActionResult EditEventData()
        {
            int ID = Convert.ToInt32(Request.Form["EID"]);
            string Name = Request.Form["Name"];
            string Email = Request.Form["Email"];
            string Phone = Request.Form["Phone"];
            string Date = Request.Form["Date"];
            string Time = Request.Form["Time"];
            string IsPublic = Request.Form["isPublic"];
            string Description = Request.Form["Description"];
            d.ChangeByQuery("update Event set Name=N'"+Name+"', Email='"+Email+"', Phone='"+Phone+"', EDate='"+Date+"', Time='"+Time+"',IsPublic='"+IsPublic+"',Description=N'"+Description+"' where ID="+ID);
            return RedirectToAction("Manage");
        }
        public ActionResult Manage()
        {
            EOrgID = Convert.ToInt32(Session["CurrentUserID"]);
            //Check if there is event or not. Retrieve EOrgID from Session. 
            if (d.CheckByQuery("select * from Event where EOrgID=" + EOrgID) == false)
            {
                return RedirectToAction("NotFound");
            }

            return View();
        }
        public ActionResult NotFound()
        {
            return View();
        }
        #endregion


        //SetRowDetail, InsertRowDetail, SetSeatStatus, InsertSeatStatus, checkArrive, SellSeatManually, PrintTicketInfo
        #region Seat
        public ActionResult SetRowDetail()
        {
            string E_EID = Request.QueryString["E_EID"];
            E_EID = E_EID.Replace(" ", "+");
            String EID = dp.Decrypt(E_EID, "ETicket");
            ViewBag.EID = Convert.ToInt32(EID);
            return View();
        }
        public ActionResult InsertRowDetail()
        {
            int EID = Convert.ToInt32(Request.Form["EID"]);
            int Row = Convert.ToInt32(Request.Form["Row"]);
            int NumberOfSeat = Convert.ToInt32(Request.Form["NumberOfSeat"]);
            string StartingCharacter = Request.Form["StartingCharacter"];
            int Price = Convert.ToInt32(Request.Form["Price"]);
            //When a row is updated, Row/Seat/CustomerTicket are deleted.
            d.ChangeByQuery("update Row set NumberOFSeat=" + NumberOfSeat + ",StartingCharacter='" + StartingCharacter + "',Price=" + Price + " where EID=" + EID + " and Row=" + Row);
            d.ChangeByQuery("delete from CustomerTicket where SeatID in(select ID from Seat where EID=" + EID + " and Row=" + Row + ")");
            d.ChangeByQuery("delete from Seat where EID=" + EID + " and Row=" + Row);
            for (int i = 1; i <= NumberOfSeat; i++)
            {
                string Name = StartingCharacter + i;
                d.ChangeByQuery("insert into Seat values(" + EID + ",'" + Name + "'," + Row + "," + Price + ",'Free')");
            }
            string url = Session["url"].ToString();
            Response.Redirect(url);
            return View();
        }
        public ActionResult SetSeatStatus()
        {
            string E_EID = Request.QueryString["E_EID"];
            E_EID = E_EID.Replace(" ", "+");
            String EID = dp.Decrypt(E_EID, "ETicket");
            ViewBag.EID = Convert.ToInt32(EID);
            return View();
        }
        public ActionResult CheckIn()
        {
            string E_EID = Request.QueryString["E_EID"];
            E_EID = E_EID.Replace(" ", "+");
            String EID = dp.Decrypt(E_EID, "ETicket");
            ViewBag.EID = Convert.ToInt32(EID);
            return View();
        }
        public ActionResult CheckArrive()
        {
            int ID = Convert.ToInt32(Request.Form["ID"]);//SeatID
            string Status = Request.Form["Status"];
                d.ChangeByQuery("update Seat set Status='" + Status + "' where ID=" + ID);
                string url = Session["url"].ToString();
                Response.Redirect(url);
                return View();
        }
        public ActionResult PrintTicketInfo()
        {
            //Descript SeatID
            string E_SeatID = Request.QueryString["E_SeatID"];
            E_SeatID = E_SeatID.Replace(" ", "+");
            String SeatID = dp.Decrypt(E_SeatID, "ETicket");
            ViewBag.SeatID = Convert.ToInt32(SeatID);

            //If SeatID is not sold, redirect to 404. That mean there is no customer
            int ID = Convert.ToInt32(SeatID);
            if(d.getStringByQuery("select * from Seat where ID="+ID,"Status") != "Sold")
            {
                return RedirectToAction("NotFound");
            }

            //Descript Event ID

EventTicket/Views/EOrg/AddSMSGate.cshtml
@using EventTicket.App_Code;
@using System.Data;
@{
    ViewBag.Title = "AddSMSGate";
    Layout = "~/Views/Shared/EOrg.cshtml";
    Base b = new Base();
    int EOrgID = Convert.ToInt32(Session["CurrentUserID"]);
    DataTable dt = b.getAllByQuery("select * from SMSGateway where EOrgID=" + EOrgID);
}

@using (Html.BeginForm("InsertSMSGate", "EOrg"))
{
    <div class="contentHeadBox">
        <div class="row">
            <div class="col-md-6">
                <input type="text" class="form-control" name="SMSGateway" placeholder="Enter Your SMS Gate" required />
            </div>
            <div class="col-md-6">
                <input type="submit" class="btn btn-primary" value="ADD" />
            </div>
        </div>
    </div>
}

<br />
<div class="contentBodyBox">
    
        @{
            if (b.CheckByQuery("select * from SMSGateway where EOrgID=" + EOrgID) == false)
            {
                <center><img src="~/Image/Icon/404.png" /></center>
            }
            else
            {
                int i = 1;
                <table class="table table-bordered" style="background-color:#F6F9ED;">
                    <tr><th>No</th><th>SMS Gateway IP</th><th></th></tr>
                    @{ 
                        foreach(DataRow row in dt.Rows)
                        {
                            <tr><td>@i</td><td>@row["IP"].ToString()</td><td><a href="~/EOrg/DeleteSMSGate?SMSGateID=@row["ID"]"><img src="~/Image/Icon/delete.png" /></a></td></tr>
                            i = i + 1;
                        }
                    }
                </table>
            }
        }
               
</div>

EventTicket/Views/EOrg/CheckIn.cshtml
@using System.Data;
@using EventTicket.App_Code;
@{
    ViewBag.Title = "SetSeatStatus";
    Layout = "~/Views/Shared/EOrg.cshtml";
    string path_and_query = HttpContext.Current.Request.Url.PathAndQuery;
    Session["url"] = path_and_query;
    int EID = ViewBag.EID;
    EncryptParameter e = new EncryptParameter();
    Base b = new Base();
    int Row = b.getIntByQuery("select top 1 * From Seat where EID=" + EID + " order by Row desc", "Row");
    DataTable dt = b.getAllByQuery("select * from Seat where EID=" + EID + " and Status = 'Book'");
    DataTable dtSold = b.getAllByQuery("select * from Seat where EID=" + EID + " and Status = 'Free'");
    DataTable dtSeatOfBookSold = b.getAllByQuery("select * from Seat where Status='Book' or Status='Sold' order by ID desc");
    DataTable dtNamePhone = b.getAllByQuery("select * from  CustomerTicket c inner join Seat s on s.ID = c.SeatID where s.EID= " + EID + " and (s.Status='Book' or s.Status='Sold') order by s.ID desc");
    DataTable dtArriveAbsent = b.getAllByQuery("select * from Seat where EID=" + EID + " and Status = 'Sold'");
    //Get data table of SeatID of Book,Sold
    //Get data table of Name and Phone of particular SeatID
}
<br />
@using (Html.BeginForm("CheckArrive", "EOrg"))
{
    <div class="contentHeadBox">
        <div class="row">
            <div class="col-md-2">
                <select name="ID" class="form-control" required>
                    <option value="">Sold Seat(ရောင်းခုံ)</option>
                    @{
                        foreach (DataRow row in dtArriveAbsent.Rows)
                        {
                            <option value="@Convert.ToInt32(row["ID"])"> @row["Name"].ToString()</option>
                        }
                    }
                </select>
            </div>
            <div class="col-md-2">
                <select name="Status" class="form-control" required>
                    <option value="">Select Status</option>
                    <option value="Present">Arrive</option>
                    <option value="Absent">Can't Come</option>
                </select>
            </div>
            <div class="col-md-3"><center><input type="submit" class="btn btn-primary" value="ARRIVE/CAN'T COME" /></center></div>
        </div>
    </div>
                        }

<br />
<div class="contentBodyBox">
    <div class="row">
        <div class="col-md-6" style="line-height:30px;">
            @{
                for (int i = 1; i <= Row; i++)
                {
                    //Get All Seat in the Row
                    DataTable Seatdt = b.getAllByQuery("select * from Seat where EID=" + EID + " and Row=" + i);
                    foreach (DataRow row in Seatdt.Rows)
                    {
                        string TicketID = (Convert.ToInt32(row["ID"])).ToString();
                        string E_TicketID = e.Encrypt(TicketID, "ETicket");
                        string E_EID = e.Encrypt(EID.ToString(), "ETicket");
                        string Name = row["Name"].ToString();
                        string Status = row["Status"].ToString();

                        <a href="~/EOrg/PrintTicketInfo?E_SeatID=@E_TicketID&E_EID=@E_EID">
                            <span id="@Name" class="@Status">@Name</span>
                        </a>

                    }
                    <br /><br />

                }
            }
        </div>
        <div class="col-md-3" style="line-height:30px;">
            <center>
                @{
                    for (int i = 1; i <= Row; i++)
                    {
                        int Price = b.getIntByQuery("select * from Seat where EID=" + EID + " and Row=" + i, "Price");
                        <b><font class="normalText">@b.getStringByQuery("select * from Row where EID=" + EID + " and Row=" + i, "StartingCharacter") Row<img src="~/Image/Icon/RightArrow.png" /> @Price</font></b> <span>Kyats</span>
                        <br /><br />
                    }
                }
            </center>
        </div>
        <center>
            <div class="col-md-3" style="border:1px solid #CDB79E;padding:10px;max-width:150px;margin:15px">
                <span class="Free">&nbsp;&nbsp;&nbsp;</span>&nbsp;Free&nbsp;-&nbsp;@b.getCountByQuery("select * from Seat where EID=" + EID + " and Status='Free'") Seats<br /><br />
                <span class="Book">&nbsp;&nbsp;&nbsp;</span>&nbsp;Book&nbsp;-&nbsp;@b.getCountByQuery("select * from Seat where EID=" + EID + " and Status='Book'") Seats<br /><br />
                <span class="Sold">&nbsp;&nbsp;&nbsp;</span>&nbsp;Sold&nbsp;-&nbsp;@b.getCountByQuery("select * from Seat where EID=" + EID + " and Status='Sold'") Seats<br /><br />
                <span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Total&nbsp;-&nbsp;@b.getCountByQuery("select * from Seat where EID=" + EID) Seats</span>
            </div>
        </center>
    </div>

</div>
<style>
    .Free, .Book, .Sold, .Present, .Absent {
        -webkit-border-radius: 4;
        -moz-border-radius: 4;
        border-radius: 4px;
        font-family: Georgia;
        color: #ffffff;
        font-size: 15px;
        padding: 5px 5px 5px 5px;
        text-decoration: none;
        min-width: 30px;
        max-width: 50px;
        text-align: center;
    }

    .Free {
        background: lightgreen;
    }

    .Book {
        background: lightblue;
    }

    .Sold {
        background: #0c1b24;
    }
    .Present {
        background: blue;
    }
    .Absent {
        background: red;
    }
</style>
<p id="seat" style="opacity:0;">
    <!--Save (1) SeatID (2) Name, Phone Here-->
    @{
        foreach (DataRow row in dtSeatOfBookSold.Rows)
        {
            string Name = row["Name"].ToString();
            Name = Name + ",";
            @Name
        }
    }
</p>
<p id="namePhone" style="opacity:0;">
    @{
        Boolean Isfree = b.getBooleanByQuery("select * from Event where ID=" + EID, "IsFree");
        foreach (DataRow row in dtNamePhone.Rows)
        {
            string Name = row["Name"].ToString();
            string Phone = row["Phone"].ToString();
            string Bank = row["Bank"].ToString();
            string Account = row["Account"].ToString();
            string bine = "🎗️" + Name + "$🎗️" + Phone;
            if (Isfree == false)
            {
                bine = bine + "$🎗️" + Bank + "$🎗️" + Account;
            }
            bine = bine + ",";
            @bine
        }
    }
</p>
<p id="phone" style="opacity:0">
    @{
        foreach (DataRow row in dtNamePhone.Rows)
        {
            string phone = row["Phone"].ToString() + ",";
            @phone
        }
    }
</p>
<!--
For Sending Message
(1) Get Event Name
(2) Get EDate
(3) Get Time
-->
<p id="EventName" style="opacity:0;">
    @b.getStringByQuery("select * from Event where ID=" + EID, "Name")
</p>
<p id="EDate" style="opacity:0;">
    @Convert.ToDateTime(b.getDateByQuery("select * from Event where ID=" + EID, "EDate")).ToString("dd/MM/yyyy")
    @b.getStringByQuery("select * from Event where ID=" + EID, "Time")

</p>



@*
    -----------------------------------------------------------
    Showing Seat Info
        <script>
        var Seat = new Array();
        var Phone = new Array();
        var NamePhone=new Array();
        $(document).ready(function () {
            var seat = document.getElementById("seat").innerText;
            Seat = seat.split(",");
            Seat.splice((Seat.length) - 1, 1);

            var phone = document.getElementById("phone").innerText;
            Phone = phone.split(",");
            Phone.splice((Phone.length) - 1, 1);

            var namePhone = document.getElementById("namePhone").innerText;
            NamePhone = namePhone.split(",");
            NamePhone.splice((NamePhone.length) - 1, 1);
        })
        function ShowNamePhone(Name, TicketID) {
            var EventName = document.getElementById("EventName").innerText;
            var EDate = document.getElementById("EDate").innerText;
            EDate = EDate.replace('/', '-');
            EDate = EDate.replace('/', '-');
            var index = Seat.indexOf(Name);
            if (index > -1) {
                var str = NamePhone[index];
                str = str.replace('$', '\r\n');
                str = str.replace('$', '\r\n');
                str = str.replace('$', '\r\n');
                str = "Client Info?\r\n\r\n" + str;
                var strsend = "";
                strsend = strsend + "\r\n❇️-" + EventName;
                strsend = strsend + "\r\n❇️-" + Name + "[" + TicketID + "]";
                strsend = strsend + "\r\n❇️-" + EDate;
                alert(str + "\r\n" + strsend);

                var messagesent = "🎟️";
                messagesent = messagesent + EventName;
                messagesent = messagesent + "/" + Name + "[" + TicketID + "]";
                messagesent = messagesent + "/" + EDate;
            }
            return;
        }
    </script>*@

EventTicket/Views/EOrg/EditEvent.cshtml
@using EventTicket.App_Code;
@using System.Data;
@{
    ViewBag.Title = "EditEvent";
    Layout = "~/Views/Shared/EOrg.cshtml";
    //(1)Get EID from Viewbag(2)Get Old Information, (3)Place them in Placeholder
    Base b = new Base();
    int EID = ViewBag.EID;
    DataTable dt = b.getAllByQuery("select * from Event where ID=" +EID);
}

@using (Html.BeginForm("EditEventData", "EOrg"))
{
    foreach (DataRow row in dt.Rows)
    {
        //take number of TotalTicket, Name for number of seat
        int ID = Convert.ToInt32(row["ID"]);
        string Cover = row["ImageName"].ToString();
        string Name = row["Name"].ToString();
        string Email = row["Email"].ToString();
        string Phone = row["Phone"].ToString();
        string Date = Convert.ToDateTime(row["EDate"]).ToString("MM/dd/yyyy");
        string Time = row["Time"].ToString();
        string description = row["Description"].ToString();

        <div class="row">
            <div class="col-lg-6">
                <div class="contentFormBox">
                    <div class="box-body">
                        <img src="~/Image/Cover/@Cover" style="width:100%;height:auto;">
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="contentFormBox">
                    <div class="box-body">
                        <div class="form-group"><label class="col-sm-4 control-label">Name</label><div class="col-sm-8"><input type="text" name="Name" class="form-control" value="@Name" required /></div></div>
                        <div class="form-group"><label class="col-sm-4 control-label">Email</label><div class="col-sm-8"><input type="email" name="Email" class="form-control" value="@Email" required /></div></div>
                        <div class="form-group"><label class="col-sm-4 control-label">Phone</label><div class="col-sm-8"><input type="text" name="Phone" class="form-control" value="@Phone" required /></div></div>
                        <div class="form-group"><label class="col-sm-4 control-label">Date</label><div class="col-sm-8"><input type="datetime" name="Date" id="datepicker" class="form-control" value="@Date" required /></div></div>
                        <div class="form-group"><label class="col-sm-4 control-label">Time</label><div class="col-sm-8"><input type="text" name="Time" class="form-control" value="@Time" required /></div></div>
                        <div class="form-group">
                            <label class="col-sm-4 control-label">Feature</label>
                            <div class="col-sm-8">
                                <div class="form-group">
                                    <input type="radio" name="isPublic" value="FALSE" checked> Private
                                    <input type="radio" name="isPublic" value="TRUE"> Public
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="contentFormBox">
                    <div class="box-body">
                        <div class="col-sm-12">
                            <textarea class="form-control" rows="7" name="Description" placeholder="" required>@description</textarea>
                        </div>
                    </div>
                    <center><input type="hidden" name="EID" class="btn btn-primary" value="@ID" /><input type="submit" class="btn btn-primary" value="EDIT" /></center>
                </div>
            </div>
        </div>
    }
}

<script>
  $( function() {
    $( "#datepicker" ).datepicker();
  } );
</script>

EventTicket/Views/EOrg/NotFound.cshtml
@{
    ViewBag.Title = "NotFound";
    Layout = "~/Views/Shared/EOrg.cshtml";
}

<br />
<br />
<center><img src="~/Image/404.png" /></center>

EventTicket/Views/EOrg/SeeBookingList.cshtml
@{
    ViewBag.Title = "SeeBookingList";
    Layout = "~/Views/Shared/EOrg.cshtml";
    Base b = new Base();
    int EID = ViewBag.EID;
}
@using System.Data;
@using EventTicket.App_Code;

<div class="contentBodyBox">
<table id="displayTable" class="table table-dark table-hover">
    <thead>
        <tr><th>No</th><th>Seat</th><th>TicketID</th><th>Name</th><th>Phone</th><th>Date</th></tr>
    </thead>
    <tbody>
        @{
            int i = 1;

            DataTable dt = b.getAllByQuery("select * from Seat where EID="+EID+" and Status='Book'");
            foreach (DataRow row in dt.Rows)
            {
                int TicketID = Convert.ToInt32(row["ID"]);
                string Seat = row["Name"].ToString();
                string Date = Convert.ToDateTime(b.getDateByQuery("select * from CustomerTicket where SeatID="+TicketID,"InsertedDate")).ToString("dd/MM/yyyy");
                String Name = b.getStringByQuery("select * from CustomerTicket where SeatID=" + TicketID, "Name");
                String Phone = b.getStringByQuery("select * from CustomerTicket where SeatID=" + TicketID, "Phone");
                <tr><td>@i</td><td><font class="normalText">@Seat</font></td><td><font class="normalText">@TicketID</font></td><td><font class="normalText">@Name</font></td><td><font class="normalText">@Phone</font></td><td><font class="normalText">@Date</font></td></tr>
                i++;
            }
        }
    </tbody>
</table>
</div>